import {
  Brush,
  Gamepad2,
  ShoppingBag,
  Sparkles,
} from "lucide-react";

import type { AppItem } from "@/types";

export const CATEGORIES = [
  "Все вещи",
  "Игры",
  "Уборка",
  "Техника",
] as const;

export const INITIAL_ITEMS: AppItem[] = [
  {
    id: 1,
    title: "PlayStation 5",
    desc: "Игровая приставка для вечера с друзьями или семейного выходного. В комплекте два геймпада и подборка популярных игр.",
    price3h: 990,
    price6h: 1490,
    price24h: 2490,
    price7d: 14900,
    icon: Gamepad2,
    color: "text-indigo-500",
    border: "border-indigo-500",
    bg: "bg-indigo-50",
    category: "Игры",
    available: true,
    active: true,
    iconKey: "gamepad",
    imageUrl: null,
    sortOrder: 10,
  },
  {
    id: 2,
    title: "PlayStation VR2",
    desc: "VR-шлем для полного погружения в игры и интерактивные впечатления. Подходит для вечеринок и необычного домашнего досуга.",
    price3h: 1190,
    price6h: 1790,
    price24h: 2990,
    price7d: 17900,
    icon: Gamepad2,
    color: "text-violet-500",
    border: "border-violet-500",
    bg: "bg-violet-50",
    category: "Игры",
    available: true,
    active: true,
    iconKey: "gamepad",
    imageUrl: null,
    sortOrder: 20,
  },
  {
    id: 3,
    title: "Робот-мойщик окон",
    desc: "Поможет быстро отмыть окна без риска и лишней возни. Особенно полезен для больших окон, лоджий и труднодоступных стекол.",
    price3h: 790,
    price6h: 1190,
    price24h: 1990,
    price7d: 11900,
    icon: Sparkles,
    color: "text-cyan-500",
    border: "border-cyan-500",
    bg: "bg-cyan-50",
    category: "Уборка",
    available: true,
    active: true,
    iconKey: "sparkles",
    imageUrl: null,
    sortOrder: 30,
  },
  {
    id: 4,
    title: "Моющий пылесос для мебели",
    desc: "Для глубокой чистки дивана, кресел, матраса или салона автомобиля. Хороший вариант перед гостями или после переезда.",
    price3h: 690,
    price6h: 990,
    price24h: 1690,
    price7d: 9900,
    icon: Brush,
    color: "text-emerald-500",
    border: "border-emerald-500",
    bg: "bg-emerald-50",
    category: "Техника",
    available: true,
    active: true,
    iconKey: "vacuum",
    imageUrl: null,
    sortOrder: 40,
  },
  {
    id: 5,
    title: "Набор для быстрой уборки",
    desc: "Комплект для бытовой уборки после ремонта, вечеринки или генеральной чистки. Удобно взять на несколько часов.",
    price3h: 490,
    price6h: 790,
    price24h: 1290,
    price7d: 7900,
    icon: ShoppingBag,
    color: "text-rose-500",
    border: "border-rose-500",
    bg: "bg-rose-50",
    category: "Уборка",
    available: true,
    active: true,
    iconKey: "package",
    imageUrl: null,
    sortOrder: 50,
  },
];
